### ISSUE TITLE
Missing AWS Region

### ISSUE THREAD

**Issue by ardiantutomo** [rumblefishdev/hardhat-kms-signer#3]
Hi, I can't deploy my contract using AWS KMS. I got error like this. Where is the config file?

Thanks.

```
Uncaught Error [ConfigError]: Missing region in config
    at finish (/Users/ardiant.utomo/Code/Test/node_modules/.pnpm/aws-sdk@2.1069.0/node_modules/aws-sdk/lib/config.js:396:7)
    at /Users/ardiant.utomo/Code/Test/node_modules/.pnpm/aws-sdk@2.1069.0/node_modules/aws-sdk/lib/event_listeners.js:86:9
    at callNextListener (/Users/ardiant.utomo/Code/Test/node_modules/.pnpm/aws-sdk@2.1069.0/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at Request.callListeners (/Users/ardiant.utomo/Code/Test/node_modules/.pnpm/aws-sdk@2.1069.0/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.VALIDATE_REGION (/Users/ardiant.utomo/Code/Test/node_modules/.pnpm/aws-sdk@2.1069.0/node_modules/aws-sdk/lib/event_listeners.js:94:47) {
  code: 'ConfigError',
  time: 2022-07-14T08:11:40.108Z
}
```

**Comment by cezary-stroczynski** [comment]
type in your console:
`export AWS_REGION={your aws region}`

**Comment by ardiantutomo** [comment]
I've solved it by using this command:
```AWS_SDK_LOAD_CONFIG=1```

Thanks!
